### ISSUE TITLE
Research stats for the Design System

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/VRMS#1048]
### Overview
The design system team are looking for stats to assist for their user research outcome.

### Action Items
- [ ] How many people onboarded in 2020, 2021 and 2022? Where there any trends in months?
- [ ] Do we know how many people onboarded on average for the last 5 years (before the pandemic and WFH activities)?
- [ ] How many people signed up for the onboarding session vs how many people actually attended the onboarding session? (can we date back to early 2021?)
- [ ] Do we know how many people joined and left projects in 2021? 
- [ ] Do we know -  of the people joined and left, in which roles were they in?
- [ ] How many dropped out after the Hack for LA onboarding session? For 2021 can we see the percentage of people who move on to onboard a team/program? (Github activity vs non-activity.) 
- [ ] Can we measure the volunteer turnover per project (information perhaps found in role call sheet or otherwise through Github issue activities.)

**Comment by JeannyRen** [comment]
These topics were discussed during the March 7 PM Design Systems meeting. Jeanette subsequently attended the VRMS team's general meeting. Please read the following answers below.

- How many people onboarded in 2020, 2021 and 2022? Were there any trends in months? 
   - Answer: VRMS team can provide the number of people that signed into VRMS for onboarding meeting.
  
- Do we know how many people onboarded on average for the last 5 years (before the pandemic and WFH activities)?
   - Answer: VRSM goes back to 3 to 6 months before the pandemic started. What are the sign-ins for all the onboarding meetings and check out the exact date when HfLA moved to online onboarding (note: will be signaled in the title of event itself)? Note for the commenter: before the pandemic onboarding happened in-person.

- How many people signed up for the onboarding session vs how many people actually attended the onboarding session? (can we date back to early 2021?)
   - Answer: check the registered vs signed in for the VRMS onboarding meeting. You can measure the percentages of shows versus no-shows. (Where is the registered data?)
  
- Can we measure the volunteer turnover per project (information perhaps found in role call sheet or otherwise through Github issue activities.) 
   - Answer: check the rosters for a good proxy, look back at the editing history. Idea to save time: classifying projects into e.g. high or low turnover. Subsequently, sample within those project categories and measure the turnover. 

**For later, if time permits**
- Do we know how many people joined and left projects in 2021? (Time from first to last checkin for each team).
   - Answer: check the rosters for a good proxy, look back at the editing history. Idea to save time: classifying projects into e.g. high or low turnover. Subsequently, sample within those project categories and measure the turnover. 
- Do we know - of the people joined and left, in which roles were they in? 
  - Answer: look at procedure described above.
- How many dropped out after the Hack for LA onboarding session? For 2021 can we see the percentage of people who move on to onboard a team/program? (Github activity vs non-activity.) 
   - Note from the VRMS team: You can track this through a good first issue. Note from Jeanette: This would actually be a good idea to output through an onboarding procedure.

**Comment by FoxShaunR** [comment]
@JeannyRen Do you need anything else from us for this?

**Comment by JackHaeg** [comment]
Closed, answers provided in comments above
