### ISSUE TITLE
Remove the ability to edit anything for the people who are not admin

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1143]
### Overview
We spoke to bonnie, and because we do not have an audit feature, we do not want to let the people in hack for la.

This is only removing the edit field from the project lead admins,

and it needs to have a disclaimer on the page that says  - 'The data here is only test data and is not accurate'

### Action Items
- [x] remove the edit ability on the projects page for the limited admin users
- [x] needs to have a disclaimer on the page that says  - 'The data here is only test data and is not accurate'
- [ ] edit the md file that is linked on our github

### Resources/Instructions

https://github.com/hackforla/VRMS/pull/1146#issuecomment-1161168843

**Comment by chukalicious** [comment]
I have a branch with the work that solves this issue. I would like to the PR for issue #1152 be merged before I push and do a rebase because I would like to avoid a merge conflict, since I'm working in the same files. If anyone has advice on preventing conflicts while working on the same files, please reach out. I'm in dire need of guidance there 😅

**Comment by chukalicious** [comment]
Hi @jbubar ! I have a question about the second action item: 

- How should we edit the md file? What info would be included in it?

**Comment by chukalicious** [comment]
[https://www.loom.com/share/9a6eb96c0cef4e238d8c610f3fd27a20](url)
