### ISSUE TITLE
Add 'Status' field to Project details form (Active, Complete, On Hold, Archive, Delete)

### ISSUE THREAD

**Issue by juliagab56** [hackforla/VRMS#1151]
### Overview
We need to add a 'Status' dropdown field in the Projects details form when creating or editing a project. This will include the options: Active, Complete, On Hold, Archive, and Delete.

### Action Items
- [x] Define specs
    - [x] Active
    - [x] Completed
    - [x] On Hold
    - [x] Archive
    - [x] Delete
- [x] Create multiple desigs within the Project Details page (#1408)

### Resources/Instructions
- This will also delete/archive meeting times (confirm this with Bonnie, last time she said users need to delete events first, and then they can delete the project)
- #1532 
- [Figma (march/28)](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/%F0%9F%96%8C%EF%B8%8FVRMS-Design%F0%9F%96%8C%EF%B8%8F?type=design&node-id=2627%3A5562&mode=design&t=WN0HgwNBKuCeMfzP-1)

<details>
<summary>On Hold / Deleted Modal</summary>
<br>
<img width="887" alt="Screenshot 2024-04-04 at 6 38 03 PM" src="https://github.com/hackforla/VRMS/assets/134463646/26858920-0564-424f-acf2-b8922d32208a">
</details>

<details>
<summary>Project Status Dropdown</summary>
<br>
<img width="259" alt="Screenshot 2024-04-04 at 6 43 24 PM" src="https://github.com/hackforla/VRMS/assets/134463646/50420ec3-abc2-43dc-a52e-5e39ea5ba9b8">
</details>

<details><summary>View Project Status</summary>
<p>
<img width="1237" alt="Screenshot 2024-04-04 at 6 51 58 PM" src="https://github.com/hackforla/VRMS/assets/134463646/fcee15a7-0986-4e08-b108-e140c21af9fe">

</p>
</details> 

<details><summary>Restore Deleted Project (Admin only)</summary>
<p>
<img width="1155" alt="Screenshot 2024-04-04 at 6 50 30 PM" src="https://github.com/hackforla/VRMS/assets/134463646/f5ef5d8a-1d66-4c35-acac-df31eac66db9">

</p>
</details>

**Comment by juliagab56** [comment]
Issue needs to be checked and prioritized by PMs

**Comment by juliagab56** [comment]
[Figma designs](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?type=design&node-id=2343%3A7785&mode=design&t=aWEFDAKzpxT5krJo-1) NOT REVIEWED

**Comment by JackHaeg** [comment]
@juliagab56 Do you mind re-writing this issue to more clearly define the more recently discussed functionality of the delete / archive statuses (that are provided via the status dropdown, instead of buttons)? Or, please feel free to close this issue completely to if you feel it's no longer relevant. 

Evan's PR: https://github.com/hackforla/VRMS/pull/1518 was related to the initial issue description, and has since been closed

**Comment by JackHaeg** [comment]
Added time-sensitive label because this feature needs to be prioritized above other features in the milestone. Without this feature, any new projects created either accidentally or created for a test cannot be deleted without editing the database directly, and we don't know if when the database is edited, if the person deleting the project is also deleting related events (which is required when you delete a project). 

Next steps: 
- Create finalized issues for development

**Comment by juliagab56** [comment]
[Figma mock ups April/8](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/%F0%9F%96%8C%EF%B8%8FVRMS-Design%F0%9F%96%8C%EF%B8%8F?type=design&node-id=2916%3A4732&mode=design&t=3ya6XBFDbJH97Uzs-1)
