### ISSUE TITLE
Refactor Location Selection Flow 

### ISSUE THREAD

**Issue by AmandaGlover-PM** [hackforla/VRMS#1221]
### Overview
* Offer preset values we don't know how they are determined yet. 
* Create a drop down
* Preselect the remote link

#### Challenges
* Ideally if they select in person, we would need another field that asks them for the address.  
* For remote - the video conference link is saved on the event not on the project
* How to process hybrid events - remote and in-person
* How to manage multiple locations 
* Are hybrid events compatible with the

**Comment by JackHaeg** [comment]
Closing as unplanned - we will be integrating location into the Create/Edit Event feature instead of the Project Details. New issue will be written to develop this functionality, which will perform similarly to Project Details location implementation: 
<img width="461" alt="Screenshot 2024-02-08 at 6 30 40 PM" src="https://github.com/hackforla/VRMS/assets/134463646/0645f691-329c-48ee-aafd-d56f4a6a3e00">
