### ISSUE TITLE
Stakeholder Feedback: Define Project Status

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1532]
### Overview
Currently project statuses have yet to be defined fully, so we need stakeholder feedback from Bonnie to clearly define each project status.

### Action Items
- [x] Define the following statuses: 
   - [x] On Hold
   - [x] Archived
   - [x] Completed 
   - [x] Active
   - [x] Deleted
- [x] Add information to wiki

### Resources/Instructions
[Figma VRMS](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?type=design&node-id=3%3A7&mode=design&t=RCmmjnyZ96GhCK0m-1)

**Comment by JackHaeg** [comment]
@juliagab56 Here's the first issue we discussed. Please feel free to add additional information to the ticket for the definitions you require

**Comment by ExperimentsInHonesty** [comment]
### Active
A project that current has assigned team members and has meetings.
### On Hold
A project that we might bring back in the future.  It is waiting to be prioritized.

### Completed
A project that we have wrapped up.

### Archived
A project that did not get completed and that we will not be reactivating.

### Deleted
A project that was created as a test, or otherwise is not real.

**Comment by ExperimentsInHonesty** [comment]
This information should get moved to the wiki

**Comment by ExperimentsInHonesty** [comment]
### Image from current designs about how this will work on projects

![image](https://github.com/hackforla/VRMS/assets/37763229/930cde95-8f14-4042-a191-a78b640ee3d0)

**Comment by JackHaeg** [comment]
Added Information about the Project status to the wiki here: https://github.com/hackforla/VRMS/wiki/Updated-VRMS-Product-Specs

**Comment by JackHaeg** [comment]
Added Information about the Project status to the wiki here: https://github.com/hackforla/VRMS/wiki/Updated-VRMS-Product-Specs
