### ISSUE TITLE
Add users to Github repo

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#174]
### Overview
A project leader should have the option to add a user to the github repository for their project. Check to see if the user has 2FA and privacy = public. 

### Actions
- [x] Connect to the Github API
- [x] Add button to project leader dashboard roster component 
- [x] Allow granting access to repository with API call
- [ ] Move credentials into environment variables
- [ ] Receive dynamic project info in query (currently hard-coded)

### Resources
Research Github API 2FA process. 
https://developer.github.com/v3/repos/collaborators/

**Comment by shiningjustice** [comment]
**Progress**: Added GitHub API integration that uses dummy data and a test github organization.

- adds endpoint
- splits up "onboarding" button on PL dashboard and adds github button

Checks if user is in organization and sends an invite to them if not. Adds them as a collaborator to the repository if they are already in organization, otherwise an invite is sent to join the repository.

**Blocks**: Pending wireframe (how to visually handle onboarding progress) and database update (to persist user status across different projects and reduce fetch calls)

**Availability**: Most of weekdays for working hours

Note: Will need to pivot from adding as collaborator to adding to team

**Comment by shiningjustice** [comment]
**Progress**: Pivoted from adding as collaborator of repo to adding to team (per the current Github team structure (e.g., `vrms-team` > `vrms-managers` > `vrms-admins`)

**Availability**: Relatively free this week

**Comment by sarL3y** [comment]
Progress: Requirements: Move credentials into environment variables. Receive dynamic project info in query (currently hard-coded).

**Comment by ExperimentsInHonesty** [comment]
@sarL3y It looks like there is a branch for this..  Can this be handed off to another developer.  Possibly @jeremyhilado

**Comment by sarL3y** [comment]
@ExperimentsInHonesty This can be handed off. The development branch has the current progress. The credentials and API calls have been hard coded to a test organization that Phoebe created. Will need to grab dynamic github data from projects and the proper credentials from the HFLA org account.

**Comment by alex-anakin** [comment]
The existing solution should be reviewed @alex-anakin

**Comment by alex-anakin** [comment]
@alex-anakin 
1. check the `project` data structure
2. check the `project` API

**Comment by alex-anakin** [comment]
Obsolete
