### ISSUE TITLE
Put Zoom link into the data model and adding to db

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#214]
### Overview
We need zoom info in the event and project models

### Action Items

- [x] Add to model documentation
- [x] Add to code
- [ ] Add to DB
- [ ] Setup routes

**Comment by sarL3y** [comment]
@ExperimentsInHonesty The zoom link is included in the project model under the "videoConferenceLink" field. They are most likely not accurate because I populated the fields with whichever link was most recent in their project's Slack channel. 

The event model has a "project" field that populates itself with the corresponding project, so the link can be pulled using an event or project API call.

**Comment by rachelwhaley** [comment]
1. In progress
2. No blockers yet, will probably need assistance when I get to routes
3. Weekends
4. ETA = this week

**Comment by rachelwhaley** [comment]
1. Model.js files for Event and recurringEvent have been updated. 
2. Blockers: not sure what is needed for route and adding to db. Do we need to add test data with links?
3. Wednesday evening
4. ?

**Comment by alex-anakin** [comment]
@rachelwhaley let's skip route and add the field to DB. Please use fake data for links.

**Comment by alex-anakin** [comment]
Done
