### ISSUE TITLE
Add Civic Opportunity project to the project database

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#237]
### Overview
The meeting times on the hackforla website are driven by an VRMS api.  So incoming requests for changes to that page, have to be sent here to be updated manually.  We need to add this new project the output.

### Action Items
- [x] Add meeting time: 
   - [x] Sundays 9:00am-10:00am Team Meeting
   - [x] Tuesday 12:00pm-1:00pm Team Meeting

### Resources/Instructions
[Civic Opportunity project details card](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/civic-opportunity-project.md)
[Hack for LA team meetings page](https://www.hackforla.org/project-meetings)

**Comment by clockwerkz** [comment]
Currently, the project model does not have any meeting times in it's schema. So the model needs to be edited with some sort of meeting time property, and ideally it would be one that would be some sort of universal time that can be adjusted to the client's timezone?

**Comment by clockwerkz** [comment]
**Progress** - Reviewing our options to use the recurringevents collection to populate the team meetings page on the website.
**Blockers** - None
**Availability** - Mon-Fri after 6 PM

**Comment by rfambro2** [comment]
Following up on the Civic Opportunity Project. Not sure who to chat with about getting this on the webisite? @clockwerkz

**Comment by clockwerkz** [comment]
@rfambro2 Yep, I'll add it in this afternoon.

**Comment by rfambro2** [comment]
@clockwerkz - Awesome, thanks!

**Comment by clockwerkz** [comment]
I have added the weekly meeting to the recurringevents database.

**Comment by Rankazze** [comment]
For complete User Acceptance I think we need to confirm that it publishes to the target consuming destination.  This meeting time is not showing on the following page https://www.hackforla.org/project-meetings.  Moving to UAT swim lane for follow up

**Comment by clockwerkz** [comment]
Yep. This is a result of dependencies that are not defined. This is the what the website is currently fetching from the recurringevents api: 

![eventsAdded](https://user-images.githubusercontent.com/11682523/91648039-884b3900-ea17-11ea-9725-6c87f8878bdb.PNG)

When the page hits those 4 new entries (that I put in), it crashes with an exception error:
![website_error](https://user-images.githubusercontent.com/11682523/91648058-d7916980-ea17-11ea-8997-4ba68119caea.PNG)

I've been having to hunt down the dependencies that are down the chain with these recurringevents (location property is required for the cron job to generate a new event, for example).  The first place I looked at when I started creating these new entries was the data model on the back end:
https://github.com/hackforla/VRMS/blob/master/models/recurringEvent.model.js

Notice there are no "required" fields in this model. These need to be added in to prevent future issues where missing dependencies will crash the applications. 

As far as this issue is concerned, I'll need to contact the members of each of the those projects and get some further info on their project/events in order to add the required data in.

**Comment by clockwerkz** [comment]
Ok, I've added in entries in the Projects collection with some of the info required by the website. The site appears to be displaying the new entries correctly.

**Comment by clockwerkz** [comment]
Status: Waiting for Civic Opportunity to verify the project is showing up correctly on the website.

**Comment by rfambro2** [comment]
@clockwerkz - Just responded to your Slack message. Weekly meetings now occur on Sundays at 9am and Tuesdays at 12pm.

**Comment by Rankazze** [comment]
Confirmed times are posting to HfLA website.  Above is Approval from Customer.
