### ISSUE TITLE
Add meeting time for Civic Tech Structure team

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#308]
### Overview
We need to add the meeting times for the Civic Tech Structure team so that they show up on their webpage

### Action Items
- [ ] See this their issue for meeting times

### Resources/Instructions
[Issue that lists meeting times](https://github.com/codeforamerica/brigade-playbook/issues/7)
[Civic Tech Structure page on hackforla.org](https://www.hackforla.org/projects/civic-tech-structure)

**Comment by clockwerkz** [comment]
Status: In-progress
Notes: Waiting on clarification on how long the meetings for these requested time slots will be.
Blockers: Need more info

**Comment by ExperimentsInHonesty** [comment]
@clockwerks 2 hours

**Comment by clockwerkz** [comment]
I have created recurringEvents for the three requested meeting times. Awaiting client confirmation to close..

**Comment by Rankazze** [comment]
@clockwerkz when I checked the website under Tues/Thurs/Sat  the new project with times has not yet posted.

**Comment by clockwerkz** [comment]
@Rankazze I see.. I added the meetings for the wrong group. I had asked Bonnie if this was for an existing group I should have been more specific in asking if this was for an existing group in our existing database. That's my error.

Since these are project team meetings, we'll need to enter in a new project into our system. Currently, there's only one project with "tech" in the title:
![civicTech](https://user-images.githubusercontent.com/11682523/95809050-aec0ed00-0cc2-11eb-9fbe-9484e4af0ee0.PNG)
I should be able to generate a new project in our db with info from the page url Bonnie provided.

**Comment by ExperimentsInHonesty** [comment]
@alex-anakin When can this get resolved?  Even when manual it should take no more than two weeks and this has been outstanding for almost a month now.

**Comment by ExperimentsInHonesty** [comment]
@alex-anakin please provide an update @switchzer0 @Rankazze

**Comment by alex-anakin** [comment]
@ExperimentsInHonesty Done.

**Comment by ExperimentsInHonesty** [comment]
@alex-anakin Agreed thank you.
