### ISSUE TITLE
Document VRMS API using Swagger UI

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#358]
### Overview
We need to have auto-generated API documentation. Swagger is a widely known framework for implementing this.

### Action Items
Follow documentation and article. The preferred Swagger version is 3.0.

### Resources/Instructions
* [Swagger UI](https://swagger.io/tools/swagger-ui/)
* [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express)
* [Documenting your Express API with Swagger](https://blog.logrocket.com/documenting-your-express-api-with-swagger/)

**Comment by ChrxsCrxss** [comment]
I have documented the majority of the schemas. The endpoints still have to be documented. Some front-end work may be necessary to expose the documents to the public.

**Comment by ChrxsCrxss** [comment]
**Update:** I've attempted to use Swagger Inspector and SwaggerHub to generate annotations based on request responses. I could hit the api endpoints, but could not generate annotations for some reason. I think I'll just bite the bullet and annotate the api by hand. Shouldn't be more than a couple hours of work and a cup of coffee.

Blockers: none
Availability: variable
ETA: 1 week

**Comment by peteplass** [comment]
bonnie has stated that this kind of documentation is important for v0.3 so that it persists into v0.4.

Alex states that this kind of documentation is more for use during active development and argues that it should be moved back to v0.4. 

For this document, we're going to need every API that we need in this. Alex is willing to try a config file that is generated automatically rather than writing it out by hand. This will need to be updated every time an API is changed. 

We will look for one that can be generated automatically.

**Comment by drubgrubby** [comment]
We don't have any links to any live swagger documentation.  Unless something else happens, this will need to be started from scratch.

**Comment by drubgrubby** [comment]
Because the API is moving to people depot we don't need to do this at VRMS.
