### ISSUE TITLE
Fix logout button and user's name in footer

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#378]
### Overview

The logout button doesn't work and the user's name displayed as 'undefined'.

![Logout](https://user-images.githubusercontent.com/11681030/97906782-1afaa380-1cf9-11eb-960b-938c3769d7ce.png)

**Comment by AmyMendelsohn** [comment]
## Progress
Investigating origin of issue, starting with why the user is "undefined" in "Hi, undefined: (logout)" :
1. It used to work with firebase: https://github.com/hackforla/VRMS/pull/68
2. It was broken in this PR, when firebase was removed and magic links are used instead. Specifically, the user is set to be `true` instead of the actual user with email information in hooks/useProvideAuth.js:  https://github.com/hackforla/VRMS/pull/290
## Blockers
none
## Availability
fairly flexible
## ETA
still in investigating stage

**Comment by AmyMendelsohn** [comment]
### Progress
- fixed email being undefined, so now it says "Hi email@gmail.com". Fix was to send user in verifyMe request in `user.controller.js`
- attempting to force logout by creating a new verification token when logout button clicked. Not sure if this is the best approach yet.

### Blockers
- need to learn more about how to logout and how to redirect to home page

### Availability
fairly flexible

### ETA
hopefully by next week

**Comment by drubgrubby** [comment]
Amy fixed the part of this issue that had to do with the name not showing up in the footer.  It was decided at the last meeting not to bother fixing the logout functionality on version 3 as it will (hopefully) not be around long enough for that to be worth the effort.  I am closing this issue.
