### ISSUE TITLE
Define minimum viable info/questions

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#4]
**As of 02/02/2020 Undefined**

### Overview
Identify key questions and important information needed in order to define the minimum viable product (alpha version).

### Action Items

- [x] Interview Bonnie
- [x] Interview Wes
- [ ] Interview Kegan
- [ ] Interview 2-3 individuals who have recently joined Hack for LA
- [x] Pull all the questions in the current Meetup "join this group" flow
- [x] Add Onboarding Experience Survey Questions

### Resources/Instructions
- [Hack for LA meetup](https://www.meetup.com/hackforla/)
- [Onboarding Experience Survey sent by greetbot](https://docs.google.com/forms/d/e/1FAIpQLSd3ayiHXV3IZMxu-cqTVvwnozwnwfdbwZjpbqCjom1QbgIImQ/viewform)
- [Google Doc of MVI/Q - please add questions and notes here](https://docs.google.com/document/d/1WutUSTlDg5RpcLuSZWzAb_NEwez_kDSrrIP5Sjt1Im8/edit)

**Comment by rachelwhaley** [comment]
When you RSVP to a specific Meetup event, you get 1 question about the code of conduct:
![Screen Shot 2019-12-09 at 6 48 33 PM](https://user-images.githubusercontent.com/9064317/70490936-a1d8d900-1ab4-11ea-84c9-e2c36417a645.png)

**Comment by ExperimentsInHonesty** [comment]
Slacbot questions as of 12/9/2019

1. Timestamp
2. Where did you hear about Hack for LA? (If multiple sources, which one made you try it out?) 
3. Which of the following describes your current skills?
4. Are you hoping to learn more about any of the following?
5. After you heard about Hack for LA, how did you first engage with the community?
6. How many Slack channels have you discovered and found useful in your first week since joining our Slack?
7. In how many HfLA Slack channels or DMs (direct messages) have you posted a message in your first week?
8. Did you identify someone in the following categories you could reach out to if you get stuck on something at HfLA?
9. Did you find a satisfactory way to engage with the Hack for LA community? 
10. (Optional) Care to share more detail around your previous answer about engagement? 
11. How confident are you that you will keep contributing at HfLA in the next month or so (either in person or remotely)?
12. What is your email address or Slack handle?
13. Which meetup(s) have you attended? (If applicable)
14. Email Address

**Comment by rachelwhaley** [comment]
Key question: what role(s) are you interested in?
Who are you?

- Web Developer
- UI/UX Designer
- Data Scientist
- Copywriter
- Project Manager
- Other Volunteer
