### ISSUE TITLE
Add organization to Event data model

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#43]
### Overview
We want to be able to track "organization" in the event data model, so we can filter the admin dashboard to show either Hack for LA or Unconference metrics.

### Action Items
- [ ] Add a field to the data model called Organization with the fields: 
  - hack-for-la
  - cfa-summit-2020

**Comment by sarL3y** [comment]
Updating this issue after the meeting on 2/17 where we discussed a few new fields to add to the collections. @klcapps can you please link to the grids or screenshots of the new fields?

**Comment by kelseylc** [comment]
@sarL3y to confirm we're scrapping this and replacing this with the "event_type" field which we'll add to the events data table. That way rather than 2 specific fields, this "event_type" field can be updated with any value as new events/summits/conferences occur. 
In the events table, **event_type** will be something like "hack night" vs "summit" vs "conference". The corresponding field will be **name**, with a descriptive event name, and we'll also add "session" field, which will have a text value for the session name.
