### ISSUE TITLE
Change vrms labels from Record Clearance to Expunge Assist

### ISSUE THREAD

**Issue by myrandi** [hackforla/VRMS#512]
### Overview
We need to change the team meeting designation for The Record Clearance Project so it will appear correctly on hackforla.org as **Expunge Assist**

### Is your team meeting team already displayed on hackforla.org?
- [x] yes - needs update
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
 
- Team on 1st & 3rd Mondays / PM on all other Mondays, Monday 6pm, 1 hour
- Weekly Research & Design Meeting, Tuesday 6pm, 1 hour
- Weekly Dev Meeting, Thursday 6pm, 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/record-clearance-project

*will update shortly to expunge-assist; please check both after Wed 3/24/21

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #expunge-assist
Slack @handle: @Myranda
<hr />

**Comment by drubgrubby** [comment]
@myrandi  - I've made the changes to the calendar.  Please confirm that they are correct.  

<details>
<summary>Event Calendar</summary>

![screencapture-hackforla-org-project-meetings-2021-03-25-21_36_41](https://user-images.githubusercontent.com/68244054/112578522-ed4eed80-8db2-11eb-933a-f892bce19cac.png)

</details>

I'm leaving the ticket "in progress" because the website hasn't yet changed the project page, and when they do I'll have to go back in and change the website URL in the db.

**Comment by myrandi** [comment]
Thanks @drubgrubby looks good on the calendar
