### ISSUE TITLE
Demo/Sprint Review

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#572]
### Dependencies:

~#551~
~#552~ 
~#534~

Discussed by Suvy on 5/17/2020. 

We would like to re-structure the meetings to include demos or sprint reviews. We will discuss with the dev team and re-visit on 5/24. 

Alex recommends not linking demos not to timelines but to implementations. 

Suvy suggests that timelines are customized to the team's capabilities.

**Comment by peteplass** [comment]
Blocked - Suvy absent from meeting this week.

**Comment by suvyrao** [comment]
1.Review of increments can be scheduled for every 3rd or 4th monday---Team decides
2.Work is bundled in Vertical slices so that demo of increments of working Software is possible - Front End/Back End
3. Demo will happen in Non-Prod ---do we have a non-prod env?

**Comment by peteplass** [comment]
This was discussed on 6/7 and the roadmap document was gone over: https://docs.google.com/document/d/1nc1oZZHbizpki76G-pPYLhIUT6mL89jUAWNVK_sQmrA/edit

This list has been organized and tasks have been assigned.

**Comment by peteplass** [comment]
Still have dependencies

**Comment by peteplass** [comment]
Aiming for 6/28 for first product demo (2 weeks out)

**Comment by peteplass** [comment]
Will leave this open for review on 6/28.

**Comment by peteplass** [comment]
Devs will review the demo of 0.3. Please add your notes on this issue.

Pete will review after we have dev feedback.

**Comment by drubgrubby** [comment]
Here's the URL: http://18.117.69.247/

@jbubar and I looked at this together. 

It appears to work exactly as the current development branch works locally. 

There are a couple of things that we noticed that may or may not be worth fixing: 
1) If the height of the screen shrinks it is not scrollable. 

<details>
<summary>Screen not scrolling</summary>
<img width="764" alt="Screen Shot 2021-06-30 at 2 35 19 PM" src="https://user-images.githubusercontent.com/68244054/124034783-82fca900-d9b0-11eb-91aa-3842e3742009.png">
</details>

2) There appears to be a different background image on mobile. (Is that intentional?)

<details>
<summary>Mobile beach background</summary>
<img width="456" alt="Screen Shot 2021-06-30 at 2 38 50 PM" src="https://user-images.githubusercontent.com/68244054/124035117-f3a3c580-d9b0-11eb-9c04-154f6052589e.png">

</details>

3) You can "Check In As New User" even if you haven't selected a meeting to check in to.  Check in new user should be disabled until you select a project, just like check in returning user is.

4) ~Akib's fix that no longer allows a duplicate email address doesn't produce an error message, so it just seems like it's not working.  Should add some response.~  Correction:  There is a response, but it's  in a very similar color and font as the form text, so I just didn't notice it. I'd suggest changing the error font color.

5) When I click the magic link I get a messsage that the link isn't valid.  If I reload the page I'm logged in just fine.

<details>
<summary>Error message</summary>
<img width="673" alt="Screen Shot 2021-06-30 at 4 29 26 PM" src="https://user-images.githubusercontent.com/68244054/124043710-7d0ec400-d9c0-11eb-977f-2c7fd14d34b7.png">
</details>

**Comment by akibrhast** [comment]
- [x]  Check in new user should be disabled until you select a project, just like check in returning user is.
- [ ] Fix css such that it is scrollable when the height of the page shrinks [ I am not working on this].
- [ ] Figure out and fix why clicking on a valid magic link redirects to a page with the message 'sorry, the link is not valid anymore'

**Comment by jbubar** [comment]
@akibrhast 
<details>
    <summary>for the css thing change it from `overflow: hidden;` to `overflow: auto;` on the `.home` class
</summary>

![Screen Shot 2021-06-30 at 7 36 18 PM](https://user-images.githubusercontent.com/53061723/124056492-ad635c00-d9da-11eb-8c0d-c8d32567b7f0.png)


</details>

**Comment by akibrhast** [comment]
I swear , there was a message from @jbubar  about overflow.. where did that go ? o0

**Comment by akibrhast** [comment]
>  Figure out and fix why clicking on a valid magic link redirects to a page with the message 'sorry, the link is not valid anymore'

From my investigation it seems the reason the valid magic link redirects to a page with the message 'sorry, the link is not valid anymore' has something to do with 'httpOnly' cookie .

Basically during the first navigation to the link, is when the httpOnly cookie is set. So at the moment the `useAuth` function is called the httpOnly with the token has not been set yet.  as such `auth.user` is always null or undefined during the first navigation of the link. 

At the time you refresh the page, the token cookie had already been set, and because of that the `userAuth` function now is able to retrieve the user.

I believe to this is something to do with passing useState,setState to the useAuth method. Such that it is triggered to be called when isMagicLinkValid === true

**Comment by jbubar** [comment]
@akib, sorry akib, I deleted it. got self conscious, lol.

Just change `overflow: hidden` to `overflow: auto` on the container that we want the scroll on...

you can also specify the axis with 
`overflow-y: auto; 
overflow-x: hidden;
`

**Comment by peteplass** [comment]
Next demo TBD. 
We likely need to define the demo. 

Suvy suggests demoing 0.3 in a local host area. 
Adam suggests pushing this to the first week in Aug. 
Josh suggests that 0.3 and 0.4 require separate reviews. 

Alex points out that deployment must come prior to demo. We are currently waiting on news from that. Will check in next week.

**Comment by peteplass** [comment]
The big stumbling block here is hosting. Moving to Ice box until hosting dependency is satisfied.

**Comment by maburke09** [comment]
All dependencies on this issue are closed. Are we ready for the sprint review?

**Comment by ExperimentsInHonesty** [comment]
Demo of 0.3

# Notes

Recording from Demo
https://drive.google.com/drive/folders/1L7jKHspVGyz1E6pj3S9hiplA8rHRtq6K?usp=sharing

### Make new issues for each bug
Resources: add link to dev url (dev.vrms.io) live link (vrms.io)
- [Created issue: #693 ] Create new user - needs to redirect on success
   - Create new user: no user response
   - As a new user when I signup for VRMS I need to receive a response so that I (and my browser) know it has been completed
   - Action item: Review user input chain to determine no response is given. (Functional on live site, not working on dev)
- [Created issue: #694 ] Browser does not remember email
   - Dependency: Create new user: no user response
   - Title: Login: browser does not remember email
   - Overview: As a returning user, when I login, I want the email I used previously to be remembered in the browser.
   - Action item: Check to see if create new user bug is done
- [Created issue: #696 ] No response on check-in
   - Dependency: Create new user: no user response
   - Title: Meeting check-in: no user response
   - Overview: As a new or returning user, when I check into a meeting, I need to receive a response that it has been successful or not
   - Action item: Check to see if no user response bug is done
- [Created issue: #697 ] Home link returns user to unauthenticated home page rather than authenticated home page
   - Title: Navigation: home link sends user to login screen (without logging them out)
   - Overview: We need to identify what behavior is desired when clicking the home button for a more rational user experience
   - Detail: Right now, when you are logged in and you click the home navigation item inside the application you are taken back to the outside of the app where you normally would login into a meeting.  What do we want this to do?
   - Action item: Look at Figma to see what screen is supposed to be there
                           Ask Adam what is supposed to happen
   - resource: figma link
- [Created issue: #698 ] Navigation is not consistent
   - Title: Navigation: inconsistent links
   - Overview: As a user, I want the navigation links to be consistent across the site so that I can easily find what I want from anywhere.
   - Action item: Make sure every page has the following links if you are logged in as an Admin: HOME, EVENTS, ADMIN, PROJECTS.  Project Manager's will only have one two pages to go to (list of projects they have access to, and the project detail edit page).
- [Created issue: #695] Cant log out
   - Title: Logout: can't log out
   - Overview: As the a PM, I want users to be logged out of the application on demand and on a time out so that we increase security of the applications data.
   - Action item: Determine what holds the login state and model what files are being touched by the logout process and identify what would be needed to logout and propose logout method to team, get approval, execute changes
- [created issue #691 ]POST request on dev env is broken, Need to change the custom header to send from an environment variable to a constant
   - Title: Database: post requests fail
   - Overview: When the app attempts to make a change to the database, the request fails
   - Action item: Confirm that the CUSTOM_REQUEST_HEADERS has been changed from environmental variable to a constant throughout the app
- [Created issue: #699 ] Remove “Add Event” feature (Which doesn’t work)
   - Title: Add Event: remove feature
   - Overview: Development needs to have the The Add Event component removed because it does not work and never has and it will be easier to build it from scratch if it does not exist.
   - Action item: Remove navigation link and all files related to add event component (be careful not to break anything)
- [Created issue: #700 ] Conference is spelled wrong "Video Converence Link"
  - Title: Project detail edit page: change field title 
  - Overview: We need all the words in the application to be spelled correctly so we can have a professional product
  - Action items: All places where Converences change to Conferences (editProject.js)
- [Created issue: #701 ] Bonnie will identify what needs to be hidden from PMs
   - Title: Project Detail Edit: Hide info that needs approval from PM view
   - Overview: As a Org rep, I need to have pms be able to change things themselves on their project object that do not require approval from Org so that we can reduce the amount of time spent on editing of database on their behalf
   - Detail: Additional options will be available to admin level and in future the pms will be able to change those items through a review process that will exist in 0.5.  Also, we want them to be able to see all their info, with a note saying something about reach out to the #admin slack channel to change grayed out items.
   - Action Items: Review list of items and put a check box by anything they should be able to change.
   - List of items that can be edited for bonnie to write a requirements doc for hiding
      - [ ] Name: 
      - [ ] Description: 
      - [ ] Location: 
      - [ ] DTLA
      - [ ] GitHub Identifier: 
      - [ ] GitHib URL: 
      - [ ] Slack URL: 
      - [ ] Google Drive URL:
      - [ ] Google Drive ID: 
      - [ ] HfLA Website URL: 
      - [ ] Video Converence Link: 
      - [ ] Looking For Description: 
      - [ ] Partners (comma separated): 
      - [ ] Recruiting Categories (comma separated):

### Example
```
Name: [edit]
311 Data
Description: [edit]
The 311 Data project seeks to empower local Neighborhood Councils to improve the ideation and analysis of their initiatives using the wealth of publicly available 311 data.
Location: [edit]
DTLA
GitHub Identifier: [edit]
190321758
GitHib URL: [edit]
https://github.com/hackforla/311-data
Slack URL: [edit]
https://hackforla.slack.com/archives/CJY4R382X
Google Drive URL: [edit]
https://drive.google.com/drive/u/0/folders/10_KYe3pbZqiq6reeLA8zDDeIlz-4PxWM
Google Drive ID: [edit]
10_KYe3pbZqiq6reeLA8zDDeIlz-4PxWM
HfLA Website URL: [edit]
https://www.hackforla.org/projects/311-data
Video Converence Link: [edit]
https://us04web.zoom.us/j/8358875318
Looking For Description: [edit]
Frontend Developers, Backend Developers, Backend Lead, DevOps
Partners (comma separated): [edit]
EmpowerLA
Recruiting Categories (comma separated): [edit]
```

**Comment by drubgrubby** [comment]
Tickets have been created.  Closing issue.
