### ISSUE TITLE
Create LocalStorage Service

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#592]
## Story
Relates to feature: 1.05 - Landing/Login Page - Text Field Memory

> As a returning user, I want VRMS to remember previous inputs in the landing page text field so I don’t have to retype my email address repeatedly.

## Instructions

- [x] Review the documentation below related to localStorage.
- [x] Create a  new service for storing data to client localStorage with the following methods:
      - `getItem(key)` - retrieves the value of the specified key
      - `setItem(key, value)` - sets the value of the specified key
      - `removeItem(key)` - deletes the specified key value pair
      - `clear()` - removes all values from localStorage
- [x] Write unit tests to show you can write to, and retrieve from localStorage.

Note that localStorage converts all values to strings.  You can either have the service return the string values, or convert them to other dataTypes (e.g. parse JSON, etc.)

## Reference
- [localStorage in JavaScript: A complete guide](https://blog.logrocket.com/localstorage-javascript-complete-guide/)

**Comment by piall** [comment]
### Update
I am taking this issue on behalf of Akib. Akib will be busy this week.

**Comment by piall** [comment]
@jasonwong26 I think you have told to make separate methods to follow the SOLID design principle. I have implemented it the way you said to implement it. But the problem I am facing is if I delete any value it still shows in the input box. To get the update from local storage I need to refresh. 
For the first time, everything works fine. From the input filed value stores in the local storage. When I refresh the page it gets automatically fetched by using getItem(). But when I try to modify from the input box it gets stucks. Because it doesn't get the update in real-time. 
So, maybe it would be better to implement it by making a `react custom hook` to make it dynamic. I have seen lots of implementation on the internet like that. 
@jbubar @drubgrubby @akibrhast   do you guys have any suggestions?

**Comment by jasonwong26** [comment]
Hi @mdPial,

This ticket is scoped to create a reusable service, not something tied directly to a React component.  Take a look at the subsequent tickets #593  and #594 for how I envisioned linking the service to the UI.

If you'd prefer to take a different approach that's fine too.  Happy to discuss options if you'd find that helpful.

**Comment by piall** [comment]
Hi @jasonwong26 . I made it by looking at this quote.
> As a returning user, I want VRMS to remember previous inputs in the landing page text field so I don’t have to retype my email address repeatedly.

I have no problem to make like this. Seems like you gave lots of time and effort to plan those issues. Appreciate it.

**Comment by piall** [comment]
### Status
Waiting for review
