### ISSUE TITLE
add functionality to Dropdown component

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#600]
### Dependency
#479

### Overview
The [dropdown component](https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/components/common/dropdown/dropdown.js) in the src/components/common/dropdown folder does not close when the user clicks outside of the dropdown. the only way to close the dropdown is to click one of the options or the input component.

<details>
    <summary>gif of me clicking around</summary>

![dropdown-vrms-dev-ui-kit](https://user-images.githubusercontent.com/53061723/123374733-743f6d80-d53c-11eb-8b47-d57ebc3e8251.gif)

</details>

### Action Items
- [x] wait till #479 is merged
- [x] use the useClickOutside hook in the util folder to gain the clickoutside functionality
- [ ] consider refactoring the component, and [the skills input component;](https://github.com/hackforla/VRMS/tree/development/client-mvp-04/src/components/common/inputSkills)
    - in the skills input component there is a dropdown. Maybe the dropdown component and the skills input dropdown can be a part of the same component

### Resources/Instructions

 - [client-mvp-04/src/utils/hooks/useClickOutside.js](https://github.com/jbubar/VRMS/blob/current-skills-component/client-mvp-04/src/utils/hooks/useClickOutside.js)
 - [client-mvp-04/src/components/common/dropdown/dropdown.js](https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/components/common/dropdown/dropdown.js)
 - [/client-mvp-04/src/components/common/inputSkills](https://github.com/hackforla/VRMS/tree/development/client-mvp-04/src/components/common/inputSkills)

**Comment by vadzimk** [comment]
@jbubar Just to make sure that I understood. Do you want the chips in the chip select to disappear once clicked outside of the InputSkills component - highlighted area below?
![image](https://user-images.githubusercontent.com/28674835/127220272-e2cbf188-b920-4c40-abb9-316cb59a226e.png)
Because according to Material UI the chips stay visible to remind what options were selected. https://material-ui.com/components/selects/#multiple-select 

![image](https://user-images.githubusercontent.com/28674835/127220866-90e095a7-8e76-4f85-ab72-7b99174bae3f.png)

Thus, I doubt that the suggested functionality will improve the UX, but it's up to someone else to decide, just my opinion.
Please confirm the functionality is necessary and the area outside which the click shall hide the chips.

**Comment by jbubar** [comment]
@vadzimk Sorry that I did not make it clear. The component that needs to change is not the current skills input. The component I am referring to is the dropdown component in the UI kit.

I was thinking that you could use the costum [useClickOutside hook](https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/hooks/useClickOutside.js) to achieve the click outside functionality.

**Comment by jbubar** [comment]
I updated the issue to make it clearer, let me know if that makes sense

**Comment by vadzimk** [comment]
@jbubar Is this the correct behavior? It seems to close as you described when clicked outside the drop-down.

![dropdown](https://user-images.githubusercontent.com/28674835/127369952-d1c2d33c-88d9-4ea6-b906-f2906f1dcd78.gif)

**Comment by jbubar** [comment]
Hi @vadzimk yes.. that is the functionality I was talkig about.. and not to beet a dead horse, but I was thinking that it could go on this component

<details>
    <summary>click to view</summary>

![Screen Shot 2021-07-29 at 9 17 43 AM](https://user-images.githubusercontent.com/53061723/127529278-ee75f6f9-8dad-4d3e-97a3-4588f12928ff.png)


</details>

**Comment by vadzimk** [comment]
@jbubar Turns out that the inputSkills ui element is completely independent of drop-down you pointed at lastly, bc it has its own drop-down:
`client-mvp-04/src/components/common/dropdown/dropdown.js`
`client-mvp-04/src/components/common/inputSkills/dropdown.js`

I will look into `client-mvp-04/src/components/common/dropdown/dropdown.js` bc it indeed is not closing.
