### ISSUE TITLE
 Logout: can't log out

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#695]
### Overview
As the a PM, I want users to be logged out of the application on demand and on a time out so that we increase security of the applications data

### Action Items
Determine what holds the login state and model what files are being touched by the logout process and identify what would be needed to logout and propose logout method to team, get approval, execute changes.

**Comment by evanyang1** [comment]
The logic for logging in (from email link) is in `handleAuth.js`.
Currently the handleLogout function is empty, hence the lack of logging out.
Tasks: 1. Clear token 2. Redirect to home page.

**Comment by glenflorendo** [comment]
Sorry I haven't been updating this issue!

Progress: I started off quickly but have slowed down significantly since then. I know what I need to do to move forward.

Blockers: N/A

Availability: I will dedicate much more time this week to ramp back up and hopefully finish soon.

ETA: I'll aim for next week!
