### ISSUE TITLE
Missing error handling: App breaks when an already existing user tries to register again

### ISSUE THREAD

**Issue by chukalicious** [hackforla/VRMS#783]
### Overview
Missing error handling: The app breaks when an already registered user tries to register again. It seems there is no error handling in several parts of our application

### Action Items

 - [ ] understand how errors are currently being handled in the userController.js
 - [ ] confirm if the user already exists and what response is sent
 - [ ] modify the response to get more useful information on the error
 - [ ] display error in the front end

### Resources/Instructions
https://levelup.gitconnected.com/handling-errors-in-mongoose-express-for-display-in-react-d966287f573b

**Comment by drubgrubby** [comment]
Great issue.  I think this became an issue when a developer who will remain nameless (though I'm sure Josh can guess who it was) changed the database to only accept a unique email for users.  Because there is no email validation on the input part of VRMS, it now breaks.  (It used to allow multiple users with the same email.  Not sure which is worse).

When this ticket is complete (or any time before that) we should create another ticket for making the email a unique entry in the database if it isn't already, and removing duplicate users from the database if there are any.

**Comment by glenflorendo** [comment]
**Progress:** I have started working on this issue, and I have a good idea of how to solve it.

**Blockers:** None, other than time.

**Availability:** I should have some availability this weekend.

**ETA:** I'm currently aiming for next week.
