### ISSUE TITLE
Project Leader Dashboard

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#98]
### Overview
A Project Leader should be able to view their own dashboard to open check-ins, create events for their project, and view the roster of attendees and project members.

### Action Items
- [x] Rachel to create mockup in Figma & link to this issue
- [x] Roster section of dashboard is being created in component #109 - add to Project Leader Dashboard 
- [x] Wire it up to the back end 
- [ ] Attendee list needs to display checked-in users that aren't yet on the roster at the top of the list 
- [ ] Roster list needs to properly display access status. 
- [ ] Add "add by email" input component

### Related issue (simultaneously)
- [ ] setup the google API #125 
- [ ] #174

**Comment by rachelwhaley** [comment]
See #109 for the initial VERY rough mockup link.

**Comment by ExperimentsInHonesty** [comment]
@sarL3y to review

**Comment by ExperimentsInHonesty** [comment]
@sarL3y had merged this into development with routes
add event is still in progress #92

**Comment by MasterBirdy** [comment]
Progress: Reverted onboard button back to single button. Still need to wire it up to back end.
Blocks: Busy week!
Availability: All throughout the week.
ETA: Next week, hopefully.

**Comment by MasterBirdy** [comment]
Progress: Integrated Dashboard with Google Drive API so it opens a code link, which is saved then can be used to create a token which gets saved. However, it is still using dummy data. Still needs to be wired to back end.
Blocks: No blocks.
Availability: All throughout the week.
ETA: Soon!

**Comment by shiningjustice** [comment]
**Progress**: Added GitHub API integration that uses dummy data and a test github organization. 
- adds endpoint
- splits up "onboarding" button on PL dashboard and adds github button
Checks if user is in organization and sends an invite to them if not. Adds them as a collaborator to the repository if they are already in organization, otherwise an invite is sent to join the repository.  
**Blocks**: Pending wireframe (how to visually handle onboarding progress) and database update (to persist user status across different projects and reduce fetch calls)
**Availability**: Most of weekdays for working hours

**Comment by sarL3y** [comment]
Progress: Requirements to complete: Attendee list needs to display checked-in users that aren't yet on the roster at the top of the list. Roster list needs to properly display access status. Add input form.

**Comment by ExperimentsInHonesty** [comment]
@sarL3y Can you provide the necessary info to hand this off to another developer?  or will you be taking this ticket?  @jeremyhilado has volunteered to work on this

**Comment by alex-anakin** [comment]
@alex-anakin will review the task progress

**Comment by jbubar** [comment]
We are already tracking a project leader dashboard on other issues
